version: 0.2

phases:
    build:
        commands:
            - echo 'Building Services App............'
            - echo $CODEBUILD_SRC_DIR
            - aws s3 cp s3://picscav-sensitive/app.properties $CODEBUILD_SRC_DIR/src/
            - mvn clean package
            
artifacts:
    files: '**/*'
    base-directory: 'target/PicScavAPI'
    
cache:
  paths:
    - '/root/.m2/**/*'