version: 0.2

phases:
	pre-build:
		commands:
			- ls -lah $CODEBUILD_SRC_DIR
            - aws s3 cp s3://picscav-sensitive/app.properties $CODEBUILD_SRC_DIR/src/app.properties
            - ls -lah $CODEBUILD_SRC_DIR/src/
    build:
        commands:
            - echo 'Building Services App............'
            - mvn clean package
            
artifacts:
    files: '**/*'
    base-directory: 'target/PicScavAPI'
    
cache:
  paths:
    - '/root/.m2/**/*'