version: 0.2

phases:
    build:
        commands:
            - echo 'Building Services App............'
            - mvn clean package
        
artifacts:
    files: '**/*'
    base-directory: 'target/PicScavAPI'
    secondary-artifacts:
      artifact1:
      	base-directory: $CODEBUILD_SRC_DIR_s
      	file: '**/*'
    
cache:
  paths:
    - '/root/.m2/**/*'